### PR TITLE
add server and data components

### PR DESCRIPTION
**Pull request by HELENTRISHA**

### CODE REVIEW

**Review by AnnaGosme — COMMENTED** [review]
Hi Helen, 
A few things I noticed:
-l.227 - Do you agree it would look better without the "." in the title to match the style of the other objects? 

And good catch on Ada Lovelace! 
I think if we have time later on, I'd like to add a bit more info to some of the women's contribution element, and work on the titles to make them more exciting, but we'll see if we have time for that :-)

**Comment by HELENTRISHA** [comment]
> Hi Helen,
> A few things I noticed:
> -l.227 - Do you agree it would look better without the "." in the title to match the style of the other objects?
> 
> And good catch on Ada Lovelace!
> I think if we have time later on, I'd like to add a bit more info to some of the women's contribution element, and work on the titles to make them more exciting, but we'll see if we have time for that :-)

love it sure I like it without ".".
yes all that makes our project attractive are goals . so Yes let's try to stick it in our roadmap for me :)

**Review by AnnaGosme — COMMENTED** [review]
Great :)
Can you please delete the "." as I don't have the file to do it! And then push again and I'll approve :)
Thank you!

**Review by AnnaGosme — APPROVED** [review]

**Comment by AnnaGosme** [comment]
Still need to remove "." from title line 227 (Ada Lovelace)

**Pull request merged**
